import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        brand: {
          50: "#fef2f2",
          100: "#fee2e2",
          200: "#fecaca",
          300: "#fca5a5",
          400: "#f87171",
          500: "#ef4444",
          600: "#dc2626",
          700: "#b91c1c",
          800: "#991b1b",
          900: "#7f1d1d",
        },
        neutral: {
          50: "#fafafa",
          100: "#f5f5f5",
          150: "#f0f0f0",
          200: "#e5e5e5",
          300: "#d4d4d4",
          400: "#a3a3a3",
          500: "#737373",
          600: "#525252",
          700: "#404040",
          800: "#262626",
          900: "#171717",
        },
        // Crimson Cravings Theme
        "inverse-primary": "#ffb3af",
        "surface": "#fbf9f9",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed-variant": "#454747",
        "on-surface": "#1b1c1c",
        "tertiary-container": "#747676",
        "on-primary-fixed-variant": "#930017",
        "surface-tint": "#bf0022",
        "surface-dim": "#dbdad9",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#ffb3af",
        "on-tertiary-container": "#fefefe",
        "surface-variant": "#e3e2e2",
        "outline": "#926e6c",
        "on-secondary-fixed": "#1c1b1b",
        "primary-fixed": "#ffdad7",
        "surface-container": "#efeded",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e3e2e2",
        "on-surface-variant": "#5d3f3d",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "primary": "#bd0021",
        "tertiary-fixed": "#e2e2e2",
        "surface-bright": "#fbf9f9",
        "secondary-fixed-dim": "#c8c6c5",
        "secondary": "#5f5e5e",
        "on-background": "#1b1c1c",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-container-high": "#e9e8e7",
        "inverse-on-surface": "#f2f0f0",
        "on-primary-container": "#fffeff",
        "secondary-container": "#e2dfde",
        "surface-container-low": "#f5f3f3",
        "on-primary-fixed": "#410005",
        "outline-variant": "#e7bdba",
        "tertiary": "#5c5d5e",
        "on-secondary-container": "#636262",
        "on-error": "#ffffff",
        "primary-container": "#e61e32",
        "inverse-surface": "#303031",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#474746",
      },
      spacing: {
        "card-gutter": "16px",
        "element-gap-sm": "8px",
        "section-margin": "32px",
        "element-gap-md": "16px",
        "unit": "4px",
        "container-padding": "20px"
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        "body-md": ["var(--font-be-vietnam-pro)", "sans-serif"],
        "headline-xl": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "body-lg": ["var(--font-be-vietnam-pro)", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "price-display": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "label-lg": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "label-md": ["var(--font-plus-jakarta-sans)", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "price-display": ["18px", { "lineHeight": "24px", "fontWeight": "700" }],
        "label-lg": ["16px", { "lineHeight": "20px", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "18px", "fontWeight": "600" }],
        "headline-md-mobile": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "headline-lg-mobile": ["22px", { "lineHeight": "28px", "letterSpacing": "0.1em", "fontWeight": "800" }]
      },
      animation: {
        "float": "float 6s ease-in-out infinite",
        "float-delayed": "float 6s ease-in-out 2s infinite",
        "float-slow": "float 8s ease-in-out 1s infinite",
        "pulse-soft": "pulse-soft 3s ease-in-out infinite",
        "fade-in-up": "fade-in-up 0.8s ease-out forwards",
        "fade-in-left": "fade-in-left 0.6s ease-out forwards",
        "fade-in-right": "fade-in-right 0.6s ease-out forwards",
        "slide-up": "slide-up 0.5s ease-out forwards",
        "orbit": "orbit 20s linear infinite",
        "marquee": "marquee 30s linear infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.8", transform: "scale(1.05)" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-left": {
          "0%": { opacity: "0", transform: "translateX(-30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "fade-in-right": {
          "0%": { opacity: "0", transform: "translateX(30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        orbit: {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      boxShadow: {
        "card": "0 1px 3px 0 rgba(0, 0, 0, 0.06), 0 1px 2px -1px rgba(0, 0, 0, 0.06)",
        "card-hover": "0 10px 25px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -4px rgba(0, 0, 0, 0.05)",
        "hero": "0 25px 50px -12px rgba(0, 0, 0, 0.12)",
        "button": "0 4px 14px 0 rgba(220, 38, 38, 0.35)",
      },
    },
  },
  plugins: [],
};
export default config;
